무기:
    1강:
        능력치:
            공격력: 5
        재료:
        - 테스트1 5
    2강:
        능력치:
            공격력: 10
        재료:
        - 테스트1 10
방어구:
    1강:
        능력치:
            체력: 5
        재료:
        - 테스트1 5
    2강:
        능력치:
            체력: 10
        재료:
        - 테스트1 10