무기:
    1강:
        능력치:
            공격력: 5
        재료:
        - 테스트1 5
        확률:
            성공: 100
            하락: 0
            파괴: 0
    2강:
        능력치:
            공격력: 10
        재료:
        - 테스트1 15
        확률:
            성공: 50
            하락: 30
            파괴: 0
    3강:
        능력치:
            공격력: 15
        재료:
        - 테스트1 15
        확률:
            성공: 10
            하락: 10
            파괴: 80
방어구:
    1강:
        능력치:
            체력: 5
        재료:
        - 테스트1 5
        확률:
            성공: 100
            하락: 0
            파괴: 0
    2강:
        능력치:
            체력: 10
        재료:
        - 테스트1 10
        확률:
            성공: 50
            하락: 30
            파괴: 0
    3강:
        능력치:
            체력: 15
        재료:
        - 테스트1 15
        확률:
            성공: 10
            하락: 10
            파괴: 80